package com.tanishqchcmd.timethread;

import com.cloudinary.Cloudinary;
import com.cloudinary.utils.ObjectUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.Authentication;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.multipart.MultipartFile;

import java.io.IOException;
import java.util.Map;

@Controller
public class ProfileController {

    @Autowired
    private StudentRepository studentRepository;

    @Autowired
    private Cloudinary cloudinary;

    @PostMapping("/profile/upload")
    public String uploadProfilePicture(Authentication authentication, @RequestParam("image") MultipartFile file) {
        if (file.isEmpty()) return "redirect:/dashboard";

        Student student = studentRepository.findByEmail(authentication.getName()).orElseThrow();

        try {
            // 1. Upload the image bytes straight to Cloudinary's cloud servers
            Map uploadResult = cloudinary.uploader().upload(file.getBytes(), ObjectUtils.emptyMap());

            // 2. Extract the permanent public URL generated by Cloudinary
            String imageUrl = uploadResult.get("secure_url").toString();

            // 3. Save the live URL string directly to your PostgreSQL database
            student.setProfilePicture(imageUrl);
            studentRepository.save(student);

        } catch (IOException e) {
            e.printStackTrace();
        }

        return "redirect:/dashboard?clear=true";
    }
}